### ISSUE TITLE
In FastCollinearPoints.java why do you use a separate array to sort by slope order?

### ISSUE THREAD

**Issue by sndnshr** [mincong-h/algorithm-princeton#1]

**Comment by mincong-h** [comment]
Hi @sndnshr, thanks for raising this issue. Do you mean line 24 in `FastCollinearPoints.java`, which is:

```java
Point[] sortedPoints = points.clone();
```

and why I use this separate array to sort? Is this your question?

**Comment by sndnshr** [comment]
Hi @mincong-h , I meant lines 34 and 35
` Point[] pointsBySlope = sortedPoints.clone();`
`Arrays.sort(pointsBySlope, p.slopeOrder());`

For each point p, this is supposed to take a new clone of the array sorted by natural order, right?
Why is this necessary? Can't we sort the same `sortedPoints` array again and again for sort by slope?

**Comment by mincong-h** [comment]
You're right. It should not be necessary to clone again. I added a commit 06ca7ab for this fix, could you help me to launch it on the assignment? I don't have access to this course anymore. If everything works fine, I'll merge it into master.

**Comment by mincong-h** [comment]
Hmm, this clone should be necessary. If you cancel the clone and sort the same array again and again, how can we ensure the next value of `p`? I mean

```java
Point p = sortedPoints[i]; // line 33
```

will no longer be deterministic.

**Comment by sndnshr** [comment]
:+1: Thanks for the clarification @mincong-h It's clear to me now.

**Comment by mincong-h** [comment]
You're welcome. And thanks for raising this issue.
