### ISSUE TITLE
In BruteForceCollinearPoints.java why the points array is sorted first?

### ISSUE THREAD

**Issue by bharatgupta99** [mincong-h/algorithm-princeton#2]
Isn't four for loops are check all the possible combinations.

**Comment by mincong-h** [comment]
I must admire that after 2 years I don't remember all the detail... The sort should be a preparation step before checking the duplicates. It ensures the array is unique before entering into the for-loops.

**Comment by bharatgupta99** [comment]
Thanks for the quick response! But I think check for duplicates is one of the reason of sorting because for input where every point is unique I got different output for sorted array of point and unsorted array of points.

**Comment by mincong-h** [comment]
Hmm... Sorting points allows to find all the possibilities having the same slop. It starts from the left-bottom endpoint of the line segment (point A):

```
        E
       /
      D
     /
    C
   /
  B
 /
A
```

If we want to find all the possibilities without sorting, the for-loops need to refactored. Currently, the loop only moves forward and never backward. It will miss some solutions when array is unsorted.

**Comment by bharatgupta99** [comment]
Got it! Thanks for the help.
